Repository compose-us/todastic, pull requests merged in 2018-09, with the labels that each got.

#57 Update bcrypt
  packages/storage-users/package-lock.json
  packages/storage-users/package.json
Labels: :nerd_face: needs-review

#70 Fix scaling of done todos
  packages/server-web/src/client/component/TodoItem.vue
Labels: :nerd_face: needs-review, bug

#81 Get Remove todos to work again
  packages/server-web/src/client/component/TodoItem.vue
  packages/server-web/src/client/component/TodoOptions.vue
Labels: bug, enhancement

#85 Fix/position drag broken
  packages/server-web/src/client/component/TodoList.vue
  packages/server-web/src/client/socket-connection.js
  packages/storage-events/src/__snapshots__/replay.spec.js.snap
  packages/storage-events/src/replay.spec.js
Labels: :nerd_face: needs-review, bug

#93 Add logo to login page
  packages/server-web/src/client/component/Login.vue
Labels: bug

#95 Fix syntax error in documentation for #TRACK
  packages/server-web/src/client/component/Help.vue
Labels: bug
