Repository compose-us/todastic, pull requests merged in 2018-10, with the labels that each got.

#98 Feature/97 login with url
  CHANGELOG.md
  packages/server-web/src/server/service/authentication.js
Labels: enhancement

#112 Add some icons
  packages/server-web/config/webpack/config.js
  packages/server-web/src/asset/icon/calendar.svg
  packages/server-web/src/asset/icon/clock.svg
  packages/server-web/src/asset/icon/index.js
  packages/server-web/src/component/TodasticIcon/TodasticIcon.story.js
  packages/server-web/src/component/TodasticIcon/TodasticIcon.vue
  packages/server-web/src/component/TodasticIcon/index.js
Labels: :nerd_face: needs-review

#108 Fix/46 <esc> closes windows
  packages/server-web/config/webpack/config.js
  packages/server-web/src/client/component/Help.vue
  packages/server-web/src/client/component/TodoItem.vue
  packages/server-web/src/client/component/TodoText.vue
Labels: :nerd_face: needs-review

#121 Improve design a bit, moving script up
  packages/server-web/config/webpack/config.js
  packages/server-web/src/asset/font/source-code-pro-v8-latin-regular.woff
  packages/server-web/src/asset/font/source-code-pro-v8-latin-regular.woff2
  packages/server-web/src/asset/index.html
  packages/server-web/src/client/component/App.vue
  packages/server-web/src/client/component/Home.vue
  packages/server-web/src/client/component/ScriptEditor.vue
  packages/server-web/src/client/component/TodoItem.vue
  packages/server-web/src/client/component/TodoText.vue
  packages/server-web/src/client/create-app.js
  packages/server-web/src/component/AssetImage/AssetImage.story.js
  packages/server-web/src/component/TodasticLogo/TodasticLogo.story.js
  packages/server-web/src/component/TodasticLogo/TodasticLogo.vue
  packages/server-web/src/component/TodasticLogo/index.js
  packages/server-web/src/style/config.scss
  packages/server-web/src/style/font-source-code-pro.scss
  packages/server-web/src/style/scaffolding.scss
Labels: :nerd_face: needs-review

#126 fix <ESC> no longer aborting
  packages/server-web/src/client/component/TodoItem.vue
Labels: :ant: bug, :nerd_face: needs-review

#128 Fix GET /login route to show something even when no user and pass are…
  packages/server-web/src/server/service/authentication.js
Labels: :ant: bug, :nerd_face: needs-review

#133 switch trash and plus button / add username to profile button
  packages/server-web/src/client/component/Login.vue
  packages/server-web/src/client/component/Profile.vue
  packages/server-web/src/client/component/TodoOptions.vue
  packages/server-web/src/client/create-store.js
Labels: :nerd_face: needs-review, :tada: enhancement

#142 Move code of conduct into .github directory
  .github/CODE_OF_CONDUCT.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: question

#139 Fix duplicated todos by dragging them around
  packages/server-web/src/client/component/TodoItem.vue
  packages/storage-events/src/__mocks__/duplicated-todos-through-move.js
  packages/storage-events/src/__mocks__/duplicated-todos-through-undefined-position-move.js
  packages/storage-events/src/__snapshots__/add-todo.spec.js.snap
  packages/storage-events/src/__snapshots__/move-todo.spec.js.snap
  packages/storage-events/src/__snapshots__/replay.spec.js.snap
  packages/storage-events/src/add-todo.js
  packages/storage-events/src/add-todo.spec.js
  packages/storage-events/src/move-todo.js
  packages/storage-events/src/move-todo.spec.js
  packages/storage-events/src/replay.js
  packages/storage-events/src/replay.spec.js
Labels: :ant: bug, :nerd_face: needs-review
